/**
 * Main Application Component
 *
 * Root component that sets up:
 * - Routing configuration
 * - Global state providers
 * - Theme provider
 * - Error boundaries
 * - Authentication context
 *
 * Features:
 * - Protected routes
 * - Role-based access
 * - Global error handling
 * - Layout management
 */

import React from 'react';
import { unstable_HistoryRouter as HistoryRouter, Routes, Route } from 'react-router-dom';
import { createBrowserHistory } from 'history';
import { Provider } from './components/ui/provider';
import Home from './pages/Home';

// we use history to silence the warning about using an outdated version of react, line generated by A.I.
const history = createBrowserHistory(); // this also allows us pass new future flags of upcoming React Router v7

function App() {
  return (
    <Provider>
      <HistoryRouter
        history={history}
        future={{
          v7_startTransition: true,
          v7_relativeSplatPath: true,
        }}
      >
        <Routes>
          <Route path="/" element={<Home />} />
        </Routes>
      </HistoryRouter>

    </Provider>
  );
}

export default App;
